openapi: 3.0.0
info:
  title: SamCorp Commerce API
  description: API documentation for the SamCorp Commerce platform.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Production server
paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products.
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      description: Create a new product.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: The created product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
    NewProduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
